zj: {
  model_name: din,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 640,
}

lastfm: {
  model_name: din,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 128,
}

hvideo: {
  model_name: din,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 64,
}


Cloud: {
  model_name: din,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 64,
}

aliccp: {
  model_name: din,
  embed_dim: 32,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 64,
}

